kumuluzee:
  name: trip-processor-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/TripDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5432/trip-data
      username: dbuser
      password: postgres
      max-pool-size: 20
    - jndi-name: jdbc/AnswerDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5434/answer-data
      username: dbuser
      password: postgres
      max-pool-size: 20
    - jndi-name: jdbc/AnalyzedtripDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5435/analyzed-trip-data
      username: dbuser
      password: postgres
      max-pool-size: 50
  config:
    consul:
      agent: http://localhost:8500
  health:
    checks:
      - data-source-health-check:
        type: liveness
        jndi-name: jdbc/TripDataDS
      - data-source-health-check:
        type: liveness
        jndi-name: jdbc/AnswerDataDS
      - data-source-health-check:
        type: liveness
        jndi-name: jdbc/AnalyzedtripDataDS
  metrics:
    web-instrumentation:
      - name: processor-endpoint
        url-pattern: /v1/process
  rest-client:
    registrations:
      - class: snap-to-roads-api
        url: https://roads.googleapis.com/v1/snapToRoads
        connect-timeout: 5000
        read-timeout: 5000
      - class: reverse-geocoding-api
        url: https://maps.googleapis.com/maps/api/geocode/json
        connect-timeout: 5000
        read-timeout: 5000
rest-properties:
  config:
    broken: false
app-properties:
  google-api-key: API_KEY_GOES_HERE
